### ISSUE TITLE
1.15.2 version prevents Stronghold generation

### ISSUE THREAD

**Issue by 3x1at1on** [yungnickyoung/Save-My-Stronghold#2]
If this mod was installed. Stronghold does not generate.
I have 230~ mods installed and not sure if there is a conflict somewhere but the minute I removed your mod, stronghold generated in my world.

**Comment by graeye** [comment]
I believe I'm seeing a similar problem, and this is the only mod that mentions stronghold worldgen as far as I can find.

Attempting to throw an eye of ender does nothing, not even consume the eye. /Locate does not find a stronghold.

Same pack with this mod disabled does not have these issues.

Edit: To provide more information, this is within a large (>250 mods) pack on 1.15.2. I've tested in isolation, with just SMS, and combined with Biomes of Plenty and Terraforged without this problem occuring. The behavior is as if Stronghold generation were disabled, but we don't believe that to be the case. And, with at least one tester, were able to repro the issue where a new world with SMS enabled did not /locate a stronghold. For them, disabling this mod from the pack and then generating a new world enabled /locate to find a stronghold. Any ideas would be appreciated.

**Comment by yungnickyoung** [comment]
Do you know if you have any mods that might tweak strongholds in some way?

**Comment by 3x1at1on** [comment]
> Do you know if you have any mods that might tweak strongholds in some way?

I do not have any mods that alter strongholds other than this one. My feeling this is something to do with world gen priorities. 
Please correct me if I am wrong but your mod delays stronghold generation so it won't be overwritten. What if there are multiple mods trying to generate structures in a large pack (>200 mods) and due to the delay in stronghold generation it misses the queue in world generation.

**Comment by yungnickyoung** [comment]
No, it doesn't delay stronghold generation. That was something I added early on, but it ended up not really mattering because most modders generate their structures improperly, using cascading worldgen instead of doing the proper method of going one chunk at a time. Even if I delayed the generation, it could still get overwritten by any large structures nearby. So I ended up scrapping that since it impacted performance.

**Comment by yungnickyoung** [comment]
Does this happen with every world you create? Or only sometimes?

**Comment by 3x1at1on** [comment]
> Does this happen with every world you create? Or only sometimes?

On my end the answer is yes. I generated 4 world with no strongholds, the minute I removed the mod, a stronghold generated in new chunks.

**Comment by graeye** [comment]
Same, no mods that *should* impact Stronghold generation. I see some stronghold loot calls, but nothing regarding worldgen except in SMS. We continue to get a slow trickle of pack users reporting the issue, but I cannot repro it myself.

I'll let you know if I can get someone with a repro that's also willing to do testing. Was just hoping you'd have something to try, or some way to log worldgen, etc.

Thanks!

**Comment by STOKESTER** [comment]
> If this mod was installed. Stronghold does not generate.
> I have 230~ mods installed and not sure if there is a conflict somewhere but the minute I removed your mod, stronghold generated in my world.

Do you by any chance have the repurposed structures mod installed as well? It messes with stronghold generation. if you open "repurposed_structures-strongholds.toml" and change "useVanillaStronghold = false" it should fix the issue

**Comment by tobi-polar** [comment]
I had this issue. I just discovered that repurposed strongholds messes with stronghold generation. By opening `repurposed_structures-strongholds.toml`  and changing `useVanillaStronghold = false` to `true` restarting the game, and travelling to new chunks, Strongholds seemed to start generating again.

**Comment by 3x1at1on** [comment]
> I had this issue. I just discovered that repurposed strongholds messes with stronghold generation. By opening `repurposed_structures-strongholds.toml` and changing `useVanillaStronghold = false` to `true` restarting the game, and travelling to new chunks, Strongholds seemed to start generating again.

I confirm this works. Closing this issue.
