### ISSUE TITLE
Modded strongholds

### ISSUE THREAD

**Issue by AnOnYmOuS-MD** [yungnickyoung/Save-My-Stronghold#3]
Hi there, first I'll say I'm a big fan of your other mods! I was trying this one out while also using the "End Remastered" mod and noticed that giant cave took away most of the end remastered stronghold. I was wondering if there is intentions for a config to add our own structures that need protection or if this is an issue with the other mod.

**Comment by yungnickyoung** [comment]
I ultimately can't really control how other structures generate. The onus is on them to handle generating in big caves properly.
